import Login from "./konsumen/Login";
import Dashboard from "./konsumen/Dashboard";
import Daftar from "./konsumen/Daftar";
import Profile from "./konsumen/Profile";
import Transaksi from "./konsumen/Transaksi";
import Alamat from "./konsumen/Alamat";
import TambahALamat from "./konsumen/Alamat/Tambah";
import KlasifikasiObjek from "./konsumen/Klasifikasi";
import Chatting from "./konsumen/Chatting";
import Riwayat from "./konsumen/Riwayat";
import DetailPesanan from "./konsumen/DetailPesanan";
import Checkout from "./konsumen/Checkout";
import InputPesanan from "./konsumen/InputPesanan";
import Kurir from "./konsumen/Kurir";
import BerikanRating from "./konsumen/Rating";
import baseUrl from "./baseUrl";
import Maps from "./konsumen/OpenMaps";
import RajaOngkir from "./konsumen/RajaOngkir";
import DaftarKurir from "./Kurir/DaftarKurir";
import LoginKurir from "./Kurir/LoginKurir";
import HomeKurir from "./Kurir/Home";
import Pengumuman from "./Kurir/Pengumuman";
import MapsKurir from "./Kurir/MapsKurir";
import RiwayatPemesanan from "./Kurir/Riwayat";
import Gaji from "./Kurir/Gaji";
import ChattingKonsumen from "./Kurir/ChattingKonsumen";
import ProfileKurir from "./Kurir/ProfileKurir";
import TambahAlamatKurir from "./Kurir/ProfileKurir/Tambah";
import DetailPemesanan from "./Kurir/Riwayat/DetailPemesanan";
import DetailPemansanByUser from "./Kurir/Riwayat/DetailPemansanByUser";
import RincianPendapatan from "./Kurir/Riwayat/RincianPendapatan";
import AlamatKurir from "./Kurir/AlamatKurir";
import TambahAlamatLengkapKurir from "./Kurir/AlamatKurir/Tambah";
import TopUp from "./konsumen/TopUp";
import DetailTopUp from "./konsumen/TopUp/DetailTopUp";
import RiwayatTopUp from "./konsumen/TopUp/Riwayat";
import RiwayatStatusSucces from "./konsumen/TopUp/RiwayatStatusSucces";
import TambahNomorHp from "./konsumen/Alamat/TambahNomorHp";
import ListRiwayatChatting from "./konsumen/List Riwayat Chatting";
import DetailChatting from "./konsumen/List Riwayat Chatting/DetailChatting";
import LupaPassword from "./konsumen/LupaPassword";
import TambahPasswordBaru from "./konsumen/LupaPassword/TambahPasswordBaru";
export {TambahPasswordBaru,LupaPassword,DetailChatting,TambahNomorHp,RiwayatStatusSucces,RiwayatTopUp,DetailTopUp,TopUp,AlamatKurir,TambahAlamatLengkapKurir ,RincianPendapatan,DetailPemansanByUser,DetailPemesanan,TambahAlamatKurir,ProfileKurir,ChattingKonsumen,MapsKurir,RiwayatPemesanan,Gaji,Pengumuman,LoginKurir,DaftarKurir,Login,Dashboard,Daftar,Profile,Transaksi,Alamat,TambahALamat,KlasifikasiObjek,Chatting,Riwayat,DetailPesanan,Checkout,InputPesanan,Kurir,BerikanRating,baseUrl,Maps,RajaOngkir,HomeKurir,ListRiwayatChatting}

